/* Header file generated by fdesign on Wed Mar  2 15:52:40 2011 */

#ifndef FD_Calculadora_h_
#define FD_Calculadora_h_

#include <forms.h>

/* Callbacks, globals and object handlers */

extern void button_cb( FL_OBJECT *, long );
extern void button_plus_cb( FL_OBJECT *, long );
extern void button_minus_cb( FL_OBJECT *, long );
extern void button_div_cb( FL_OBJECT *, long );
extern void button_equal_cb( FL_OBJECT *, long );
extern void button_mult_cb( FL_OBJECT *, long );
extern void button_c_cb( FL_OBJECT *, long );
extern void button_clr_cb( FL_OBJECT *, long );
extern void button_min_cb( FL_OBJECT *, long );
extern void button_mr_cb( FL_OBJECT *, long );
extern void button_sign_cb( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * Calculadora;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * lcd;
    FL_OBJECT * button1;
    FL_OBJECT * button2;
    FL_OBJECT * button3;
    FL_OBJECT * button_plus;
    FL_OBJECT * button4;
    FL_OBJECT * button5;
    FL_OBJECT * button6;
    FL_OBJECT * button_minus;
    FL_OBJECT * button7;
    FL_OBJECT * button8;
    FL_OBJECT * button9;
    FL_OBJECT * button0;
    FL_OBJECT * button_div;
    FL_OBJECT * button_equal;
    FL_OBJECT * button_mult;
    FL_OBJECT * button_c;
    FL_OBJECT * button_clr;
    FL_OBJECT * button_min;
    FL_OBJECT * button_mr;
    FL_OBJECT * button_sign;
} FD_Calculadora;

extern FD_Calculadora * create_form_Calculadora( void );

#endif /* FD_Calculadora_h_ */
