/* Form definition file generated by fdesign */

#include <stdlib.h>
#include "Dialogos.h"


/***************************************
 ***************************************/

FD_DialogoProfesor *
create_form_DialogoProfesor( void )
{
    FL_OBJECT *obj;
    FD_DialogoProfesor *fdui = (FD_DialogoProfesor *) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->DialogoProfesor = fl_bgn_form( FL_NO_BOX, 500, 245 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 500, 245, "" );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 10, 480, 30, "Nombre del profesor:" );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 100, 480, 30, UTF8ToLatin1("Correo electrónico:").c_str() );

    fdui->input_nombre = obj = fl_add_input( FL_NORMAL_INPUT, 10, 40, 480, 40, "" );
    fl_set_object_lalign( obj, FL_ALIGN_TOP );
    fl_set_object_callback( obj, input_nombre_cb, 0 );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->input_email = obj = fl_add_input( FL_NORMAL_INPUT, 10, 130, 480, 40, "" );
    fl_set_object_callback( obj, input_email_cb, 0 );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->button_aceptar = obj = fl_add_button( FL_NORMAL_BUTTON, 390, 190, 100, 40, "Aceptar" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_aceptar_cb, 0 );

    fdui->button_cancelar = obj = fl_add_button( FL_NORMAL_BUTTON, 280, 190, 100, 40, "Cancelar" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_cancelar_cb, 0 );

    fl_end_form( );

    fdui->DialogoProfesor->fdui = fdui;
    fl_set_form_atclose(fdui->DialogoProfesor, form_atclose, NULL);

    return fdui;
}


/***************************************
 ***************************************/

FD_DialogoCompanero *
create_form_DialogoCompanero( void )
{
    FL_OBJECT *obj;
    FD_DialogoCompanero *fdui = (FD_DialogoCompanero *) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->DialogoCompanero = fl_bgn_form( FL_NO_BOX, 500, 245 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 500, 245, "" );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 10, 480, 30, UTF8ToLatin1("Nombre del compañero:").c_str() );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 100, 480, 30, UTF8ToLatin1("Correo electrónico:").c_str() );

    fdui->input_nombre = obj = fl_add_input( FL_NORMAL_INPUT, 10, 40, 480, 40, "" );
    fl_set_object_lalign( obj, FL_ALIGN_TOP );
    fl_set_object_callback( obj, input_nombre_cb, 0 );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->input_email = obj = fl_add_input( FL_NORMAL_INPUT, 10, 130, 480, 40, "" );
    fl_set_object_callback( obj, input_email_cb, 0 );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->button_aceptar = obj = fl_add_button( FL_NORMAL_BUTTON, 390, 190, 100, 40, "Aceptar" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_aceptar_cb, 0 );

    fdui->button_cancelar = obj = fl_add_button( FL_NORMAL_BUTTON, 280, 190, 100, 40, "Cancelar" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_cancelar_cb, 0 );

    fl_end_form( );

    fdui->DialogoCompanero->fdui = fdui;
    fl_set_form_atclose(fdui->DialogoCompanero, form_atclose, NULL);

    return fdui;
}


/***************************************
 ***************************************/

FD_DialogoSesion *
create_form_DialogoSesion( void )
{
    FL_OBJECT *obj;
    FD_DialogoSesion *fdui = (FD_DialogoSesion *) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->DialogoSesion = fl_bgn_form( FL_NO_BOX, 500, 415 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 500, 415, "" );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 180, 480, 30, UTF8ToLatin1("Día de la semana:").c_str() );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 270, 200, 30, "Hora de inicio:" );

    fdui->input_lugar = obj = fl_add_input( FL_NORMAL_INPUT, 10, 120, 480, 40, "" );
    fl_set_object_lalign( obj, FL_ALIGN_TOP );
    fl_set_object_callback( obj, input_lugar_cb, 0 );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->button_aceptar = obj = fl_add_button( FL_NORMAL_BUTTON, 390, 360, 100, 40, "Aceptar" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_aceptar_cb, 0 );

    fdui->button_cancelar = obj = fl_add_button( FL_NORMAL_BUTTON, 280, 360, 100, 40, "Cancelar" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_cancelar_cb, 0 );

    fdui->spinner_hora = obj = fl_add_spinner( FL_INT_SPINNER, 10, 300, 60, 40, "" );
    fl_set_object_callback( obj, spinner_hora_cb, 0 );
    fl_set_spinner_bounds( obj, 0, 23 );

    fdui->spinner_minuto = obj = fl_add_spinner( FL_INT_SPINNER, 80, 300, 60, 40, "" );
    fl_set_object_callback( obj, spinner_minuto_cb, 0 );
    fl_set_spinner_bounds( obj, 0, 59 );

    fdui->spinner_segundo = obj = fl_add_spinner( FL_INT_SPINNER, 150, 300, 60, 40, "" );
    fl_set_object_callback( obj, spinner_segundo_cb, 0 );
    fl_set_spinner_bounds( obj, 0, 59 );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 10, 480, 30, "Lugar:" );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 90, 480, 30, "Lugar:" );

    fdui->choice_dia = obj = fl_add_choice( FL_NORMAL_CHOICE2, 10, 210, 480, 40, "" );
    fl_set_object_callback( obj, choice_dia_cb, 0 );
    fl_addto_choice( obj, "Lunes" );
    fl_set_choice_item_mode( obj, 1, FL_PUP_NONE );
    fl_addto_choice( obj, "Martes" );
    fl_set_choice_item_mode( obj, 2, FL_PUP_NONE );
    fl_addto_choice( obj, UTF8ToLatin1("Miércoles").c_str() );
    fl_addto_choice( obj, "Jueves" );
    fl_set_choice_item_mode( obj, 4, FL_PUP_NONE );
    fl_addto_choice( obj, "Viernes" );
    fl_set_choice_item_mode( obj, 5, FL_PUP_NONE );
    fl_addto_choice( obj, UTF8ToLatin1("Sábado").c_str() );
    fl_set_choice_item_mode( obj, 6, FL_PUP_NONE );
    fl_addto_choice( obj, "Domingo" );
    fl_set_choice_item_mode( obj, 7, FL_PUP_NONE );
    fl_set_choice( obj, 1 );

    fdui->checkbutton_practicas = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 220, 50, 130, 40, UTF8ToLatin1("Prácticas").c_str() );
    fl_set_object_callback( obj, checkbutton_practicas_cb, 0 );

    fdui->checkbutton_teoria = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 70, 50, 120, 40, UTF8ToLatin1("Teoría").c_str() );
    fl_set_object_callback( obj, checkbutton_teoria_cb, 0 );

    fdui->spinner_hora2 = obj = fl_add_spinner( FL_INT_SPINNER, 290, 300, 60, 40, "" );
    fl_set_object_callback( obj, spinner_hora2_cb, 0 );
    fl_set_spinner_bounds( obj, 0, 23 );

    fdui->spinner_minuto2 = obj = fl_add_spinner( FL_INT_SPINNER, 360, 300, 60, 40, "" );
    fl_set_object_callback( obj, spinner_minuto2_cb, 0 );
    fl_set_spinner_bounds( obj, 0, 59 );

    fdui->spinner_segundo2 = obj = fl_add_spinner( FL_INT_SPINNER, 430, 300, 60, 40, "" );
    fl_set_object_callback( obj, spinner_segundo2_cb, 0 );
    fl_set_spinner_bounds( obj, 0, 59 );

    obj = fl_add_text( FL_NORMAL_TEXT, 290, 270, 200, 30, "Hora de fin:" );

    fl_end_form( );

    fdui->DialogoSesion->fdui = fdui;
    fl_set_form_atclose(fdui->DialogoSesion, form_atclose, NULL);

    return fdui;
}


/***************************************
 ***************************************/

FD_DialogoCita *
create_form_DialogoCita( void )
{
    FL_OBJECT *obj;
    FD_DialogoCita *fdui = (FD_DialogoCita *) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->DialogoCita = fl_bgn_form( FL_NO_BOX, 500, 335 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 500, 335, "" );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 10, 480, 30, UTF8ToLatin1("Descripción:").c_str() );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 100, 480, 30, "Fecha (dd/mm/aaaa hh:mm:ss):" );

    fdui->input_descripcion = obj = fl_add_input( FL_NORMAL_INPUT, 10, 40, 480, 40, "" );
    fl_set_object_lalign( obj, FL_ALIGN_TOP );
    fl_set_object_callback( obj, input_descripcion_cb, 0 );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->button_aceptar = obj = fl_add_button( FL_NORMAL_BUTTON, 390, 280, 100, 40, "Aceptar" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_aceptar_cb, 0 );

    fdui->button_cancelar = obj = fl_add_button( FL_NORMAL_BUTTON, 280, 280, 100, 40, "Cancelar" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_cancelar_cb, 0 );

    fdui->spinner_duracion = obj = fl_add_spinner( FL_INT_SPINNER, 10, 220, 480, 40, "" );
    fl_set_object_callback( obj, spinner_duracion_cb, 0 );
    fl_set_spinner_bounds( obj, 0, 50000 );
    fl_set_spinner_step( obj, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 190, 480, 30, UTF8ToLatin1("Duración (mins):").c_str() );

    fdui->spinner_dia = obj = fl_add_spinner( FL_INT_SPINNER, 10, 130, 60, 40, "" );
    fl_set_object_callback( obj, spinner_dia_cb, 0 );
    fl_set_spinner_bounds( obj, 1, 31 );
    fl_set_spinner_value( obj, 1 );

    fdui->spinner_mes = obj = fl_add_spinner( FL_INT_SPINNER, 80, 130, 60, 40, "" );
    fl_set_object_callback( obj, spinner_mes_cb, 0 );
    fl_set_spinner_bounds( obj, 1, 12 );
    fl_set_spinner_value( obj, 1 );

    fdui->spinner_ano = obj = fl_add_spinner( FL_INT_SPINNER, 150, 130, 90, 40, "" );
    fl_set_object_callback( obj, spinner_ano_cb, 0 );
    fl_set_spinner_bounds( obj, 1900, 2100 );
    fl_set_spinner_value( obj, 1900 );

    fdui->spinner_hora = obj = fl_add_spinner( FL_INT_SPINNER, 290, 130, 60, 40, "" );
    fl_set_object_callback( obj, spinner_hora_cb, 0 );
    fl_set_spinner_bounds( obj, 0, 23 );

    fdui->spinner_minuto = obj = fl_add_spinner( FL_INT_SPINNER, 360, 130, 60, 40, "" );
    fl_set_object_callback( obj, spinner_minuto_cb, 0 );
    fl_set_spinner_bounds( obj, 0, 59 );

    fdui->spinner_segundo = obj = fl_add_spinner( FL_INT_SPINNER, 430, 130, 60, 40, "" );
    fl_set_object_callback( obj, spinner_segundo_cb, 0 );
    fl_set_spinner_bounds( obj, 0, 59 );

    fl_end_form( );

    fdui->DialogoCita->fdui = fdui;
    fl_set_form_atclose(fdui->DialogoCita, form_atclose, NULL);

    return fdui;
}


/***************************************
 ***************************************/

FD_DialogoNota *
create_form_DialogoNota( void )
{
    FL_OBJECT *obj;
    FD_DialogoNota *fdui = (FD_DialogoNota *) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->DialogoNota = fl_bgn_form( FL_NO_BOX, 500, 245 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 500, 245, "" );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 10, 480, 30, UTF8ToLatin1("Descripción:").c_str() );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 100, 480, 30, "Nota:" );

    fdui->input_descripcion = obj = fl_add_input( FL_NORMAL_INPUT, 10, 40, 480, 40, "" );
    fl_set_object_lalign( obj, FL_ALIGN_TOP );
    fl_set_object_callback( obj, input_descripcion_cb, 0 );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->button_aceptar = obj = fl_add_button( FL_NORMAL_BUTTON, 390, 190, 100, 40, "Aceptar" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_aceptar_cb, 0 );

    fdui->button_cancelar = obj = fl_add_button( FL_NORMAL_BUTTON, 280, 190, 100, 40, "Cancelar" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_cancelar_cb, 0 );

    fdui->spinner_nota = obj = fl_add_spinner( FL_FLOAT_SPINNER, 10, 130, 480, 40, "" );
    fl_set_object_callback( obj, spinner_nota_cb, 0 );
    fl_set_spinner_precision( obj, 2 );
    fl_set_spinner_bounds( obj, 0.00, 10.00 );
    fl_set_spinner_step( obj, 0.01 );

    fl_end_form( );

    fdui->DialogoNota->fdui = fdui;
    fl_set_form_atclose(fdui->DialogoNota, form_atclose, NULL);

    return fdui;
}
