/* Form definition file generated by fdesign */

#include <stdlib.h>
#include "Formulario.h"


/***************************************
 ***************************************/

FD_Calculadora *
create_form_Calculadora( void )
{
    FL_OBJECT *obj;
    FD_Calculadora *fdui = (FD_Calculadora *) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->Calculadora = fl_bgn_form( FL_NO_BOX, 296, 319 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 296, 319, "" );

    obj = fl_add_frame( FL_ENGRAVED_FRAME, 10, 10, 270, 40, "" );

    fdui->lcd = obj = fl_add_text( FL_NORMAL_TEXT, 10, 10, 270, 40, "0" );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->button1 = obj = fl_add_button( FL_NORMAL_BUTTON, 10, 190, 50, 50, "1" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_cb, 1 );

    fdui->button2 = obj = fl_add_button( FL_NORMAL_BUTTON, 70, 190, 50, 50, "2" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_cb, 2 );

    fdui->button3 = obj = fl_add_button( FL_NORMAL_BUTTON, 130, 190, 50, 50, "3" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_cb, 3 );

    fdui->button_plus = obj = fl_add_button( FL_NORMAL_BUTTON, 190, 70, 40, 40, "+" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_plus_cb, 0 );

    fdui->button4 = obj = fl_add_button( FL_NORMAL_BUTTON, 10, 130, 50, 50, "4" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_cb, 4 );

    fdui->button5 = obj = fl_add_button( FL_NORMAL_BUTTON, 70, 130, 50, 50, "5" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_cb, 5 );

    fdui->button6 = obj = fl_add_button( FL_NORMAL_BUTTON, 130, 130, 50, 50, "6" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_cb, 6 );

    fdui->button_minus = obj = fl_add_button( FL_NORMAL_BUTTON, 190, 120, 40, 40, "-" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_minus_cb, 0 );

    fdui->button7 = obj = fl_add_button( FL_NORMAL_BUTTON, 10, 70, 50, 50, "7" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_cb, 7 );

    fdui->button8 = obj = fl_add_button( FL_NORMAL_BUTTON, 70, 70, 50, 50, "8" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_cb, 8 );

    fdui->button9 = obj = fl_add_button( FL_NORMAL_BUTTON, 130, 70, 50, 50, "9" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_cb, 9 );

    fdui->button0 = obj = fl_add_button( FL_NORMAL_BUTTON, 10, 250, 170, 60, "0" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_cb, 0 );

    fdui->button_div = obj = fl_add_button( FL_NORMAL_BUTTON, 190, 220, 40, 40, "/" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_div_cb, 0 );

    fdui->button_equal = obj = fl_add_button( FL_NORMAL_BUTTON, 190, 270, 40, 40, "=" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_equal_cb, 0 );

    fdui->button_mult = obj = fl_add_button( FL_NORMAL_BUTTON, 190, 170, 40, 40, "x" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_mult_cb, 0 );

    fdui->button_c = obj = fl_add_button( FL_NORMAL_BUTTON, 240, 70, 40, 40, "C" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_c_cb, 0 );

    fdui->button_clr = obj = fl_add_button( FL_NORMAL_BUTTON, 240, 120, 40, 40, "Clr" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_clr_cb, 0 );

    fdui->button_min = obj = fl_add_button( FL_NORMAL_BUTTON, 240, 170, 40, 40, "Min" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_min_cb, 0 );

    fdui->button_mr = obj = fl_add_button( FL_NORMAL_BUTTON, 240, 220, 40, 40, "MR" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_mr_cb, 0 );

    fdui->button_sign = obj = fl_add_button( FL_NORMAL_BUTTON, 240, 270, 40, 39, "-/+" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_sign_cb, 0 );

    fl_end_form( );

    fdui->Calculadora->fdui = fdui;

    return fdui;
}
