/* Form definition file generated by fdesign */

#include <stdlib.h>
#include "Formulario.h"


/***************************************
 ***************************************/

FD_Formulario *
create_form_Formulario( void )
{
    FL_OBJECT *obj;
    FD_Formulario *fdui = (FD_Formulario *) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->Formulario = fl_bgn_form( FL_NO_BOX, 825, 533 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 825, 533, "" );

    fdui->button_abrir = obj = fl_add_button( FL_NORMAL_BUTTON, 10, 10, 110, 30, "Abrir" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_callback( obj, button_abrir_cb, 0 );

    fdui->button_guardar = obj = fl_add_button( FL_NORMAL_BUTTON, 130, 10, 110, 30, "Guardar" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_callback( obj, button_guardar_cb, 0 );

    fdui->button_anadir = obj = fl_add_button( FL_NORMAL_BUTTON, 250, 10, 150, 30, "Añadir asignatura" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_callback( obj, button_anadir_cb, 0 );

    fdui->button_quitar = obj = fl_add_button( FL_NORMAL_BUTTON, 410, 10, 150, 30, "Quitar asignatura" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_callback( obj, button_quitar_cb, 0 );

    fdui->text_lista = obj = fl_add_text( FL_NORMAL_TEXT, 10, 70, 170, 30, "Lista de asignaturas" );

    fdui->browser_asignaturas = obj = fl_add_browser( FL_NORMAL_BROWSER, 10, 100, 230, 420, "" );
    fl_set_object_callback( obj, browser_asignaturas_cb, 0 );

    fdui->button_profesores = obj = fl_add_button( FL_PUSH_BUTTON, 250, 70, 110, 30, "Profesores" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_profesores_cb, 0 );

    fdui->button_companeros = obj = fl_add_button( FL_PUSH_BUTTON, 360, 70, 110, 30, "Compañeros" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_companeros_cb, 0 );

    fdui->button_sesiones = obj = fl_add_button( FL_PUSH_BUTTON, 470, 70, 110, 30, "Sesiones" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_sesiones_cb, 0 );

    fdui->button_citas = obj = fl_add_button( FL_PUSH_BUTTON, 580, 70, 110, 30, "Citas" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_citas_cb, 0 );

    fdui->button_notas = obj = fl_add_button( FL_PUSH_BUTTON, 690, 70, 110, 30, "Notas" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_notas_cb, 0 );

    obj = fl_add_frame( FL_UP_FRAME, 250, 100, 560, 420, "" );

    fdui->button_plus = obj = fl_add_button( FL_NORMAL_BUTTON, 750, 110, 20, 20, "+" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_plus_cb, 0 );

    fdui->button_minus = obj = fl_add_button( FL_NORMAL_BUTTON, 780, 110, 20, 20, "-" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, button_minus_cb, 0 );

    fdui->browser_asignatura = obj = fl_add_browser( FL_NORMAL_BROWSER, 260, 140, 540, 370, "" );
    fl_set_object_callback( obj, browser_asignatura_cb, 0 );

    fl_end_form( );

    fdui->Formulario->fdui = fdui;

    return fdui;
}
